# Generated by Django 5.2.8 on 2025-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_is_for_others_expense_paid_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
