# Generated by Django 5.2.8 on 2025-12-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='applied_to_people',
            field=models.BooleanField(default=True),
        ),
    ]
