# Generated by Django 5.2.8 on 2025-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_applied_to_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='applied_to_people',
            field=models.BooleanField(default=False, help_text='Whether this expense should affect People ledger'),
        ),
    ]
