# Generated by Django 5.2.8 on 2025-12-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_applied_to_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='applied_to_people',
        ),
    ]
