# Generated by Django 5.2.8 on 2025-12-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_remove_expense_applied_to_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_from_people',
            field=models.BooleanField(default=False),
        ),
    ]
