# Generated by Django 5.2.8 on 2025-12-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_expense_created_from_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_from_people',
        ),
    ]
