# Generated by Django 5.2.8 on 2025-12-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='monthly_budget',
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_currency',
            field=models.CharField(choices=[('INR', '₹ INR (Indian Rupee)'), ('USD', '$ USD (US Dollar)'), ('EUR', '€ EUR (Euro)'), ('GBP', '£ GBP (British Pound)')], default='INR', max_length=3),
        ),
    ]
