# Generated by Django 5.2.8 on 2025-12-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_options'),
        ('income', '0005_income_applied_to_people'),
        ('people', '0002_personledgerentry_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personledgerentry',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_ledger_entries', to='expenses.expense'),
        ),
        migrations.AlterField(
            model_name='personledgerentry',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_ledger_entries', to='income.income'),
        ),
    ]
