# Generated by Django 5.2.8 on 2025-12-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_personledgerentry_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tracking_preference',
            field=models.CharField(choices=[('track', 'Track balances'), ('no_track', "Don't track"), ('ask', 'Ask every time')], default='ask', help_text='Controls whether we automatically track ledger changes for this person.', max_length=10),
        ),
    ]
