# Generated by Django 5.2.8 on 2025-12-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_person_tracking_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='auto_suggest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tracking_preference',
            field=models.CharField(choices=[('track', 'Track balances'), ('no_track', 'Do not track'), ('ask', 'Ask every time')], default='ask', help_text='Should Kharcha track balances with this person?', max_length=10),
        ),
    ]
