# Generated by Django 5.2.8 on 2025-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_auto_suggest_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='archived',
            field=models.BooleanField(default=False, help_text='If true, hide this person from main People list (untracked/archived).'),
        ),
        migrations.AddField(
            model_name='personledgerentry',
            name='archived',
            field=models.BooleanField(default=False, help_text='If true, this ledger row is archived and not counted in active balances.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='auto_suggest_enabled',
            field=models.BooleanField(default=True, help_text='If disabled, Kharcha will not show balance suggestions for this person.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tracking_preference',
            field=models.CharField(choices=[('TRACK', 'Track balances'), ('NO_TRACK', 'Do not track'), ('ASK', 'Ask every time')], default='ASK', help_text='Should Kharcha track balances with this person?', max_length=16),
        ),
    ]
