# Generated by Django 5.2.8 on 2025-12-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='from_person',
        ),
        migrations.AddField(
            model_name='income',
            name='person',
            field=models.CharField(blank=True, help_text='Who gave you this money? (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(blank=True, help_text="Note like 'Nov salary', 'Refund for shoes', etc.", max_length=255),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('salary', 'Salary'), ('pocket_money', 'Pocket Money'), ('refund', 'Refund'), ('gift', 'Gift'), ('repayment', 'Repayment'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
