# Generated by Django 5.2.8 on 2025-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_remove_income_from_person_income_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('salary_wages', 'Salary / Wages'), ('business', 'Business Income'), ('investment', 'Investment Income'), ('refund', 'Refund / Reimbursement'), ('gift_support', 'Gift / Support Money'), ('loan_repayment', 'Loan Repayment'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
