# Generated by Django 5.2.8 on 2025-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income_payment_type_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('salary_wages', 'Salary / Wages'), ('business', 'Business Income'), ('investment', 'Investment Income'), ('refund', 'Refund / Reimbursement'), ('gift_support', 'Gift / Allowance'), ('loan', 'Loan'), ('loan_repayment', 'Loan Repayment'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
