# Generated by Django 5.2.8 on 2025-12-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='applied_to_people',
            field=models.BooleanField(default=False, help_text='If true this income has been applied to the Person ledger (via banner or wizard).'),
        ),
    ]
